### ISSUE TITLE
Permission problem when restoring the backup

### ISSUE THREAD

**Issue by jlcanovas** [gousiosg/github-mirror#23]
Hi,

I'm in the process of restoring the last backup (20160419), I was following the indications described [here](https://github.com/gousiosg/github-mirror/tree/master/sql) and I think there is something missing to make it work.

The execution of the command `ght-restore-mysql` fails when running the `LOAD DATA INFILE` statements as the user created for the new schemata does not include the corresponding permission. 

I solved it with something like:

`GRANT FILE ON *.* TO 'ghtorrentuser'@'localhost';`

Maybe the problem appears only with specific database configurations. In my case, I'm using MySQL Commnuity Server 5.6.25 on Linux.

**Comment by gousiosg** [comment]
In the instructions on how to reload the files there is a step to grant ALL privileges to the importing user. As can be seen in the MySQL [GRANT reference](http://dev.mysql.com/doc/refman/5.7/en/grant.html) this also includes the FILE privilege.

I think the process is OK, the problem is probably local to your own installation of MySQL.

**Comment by jlcanovas** [comment]
Ops! I see. Strangely, the `grant all privileges` did not work in my machine as expected.

I guess the issue can be closed then. Thanks!
